<?php
/**
 * ONE-TIME USE ONLY.
 * Visit this file in your browser (e.g. localhost/DirectLinkHands/reset_admin_password.php)
 * to reset the admin password to a known value, generated by YOUR OWN PHP install
 * (so it is guaranteed to work with password_verify() on this server).
 *
 * DELETE THIS FILE after you've used it — it is a security risk to leave it on
 * a live server.
 */

require_once 'includes/db.php';

$newPassword = 'admin123'; // change this if you want a different password
$hashed = password_hash($newPassword, PASSWORD_DEFAULT);

$stmt = mysqli_prepare($conn, "UPDATE admin SET password = ? WHERE username = 'admin'");
mysqli_stmt_bind_param($stmt, "s", $hashed);
$ok = mysqli_stmt_execute($stmt);

$affected = mysqli_stmt_affected_rows($stmt);
?>
<!DOCTYPE html>
<html>
<head><title>Admin Password Reset</title></head>
<body style="font-family: sans-serif; padding: 40px; max-width: 600px; margin: 0 auto;">
<?php if ($ok && $affected > 0): ?>
    <h2 style="color: green;">✅ Password reset successful</h2>
    <p>The <code>admin</code> account's password has been set to: <strong><?= htmlspecialchars($newPassword) ?></strong></p>
    <p>You can now log in at <a href="login.php">login.php</a> using:</p>
    <ul>
        <li>Login As: <strong>Admin</strong></li>
        <li>Username: <strong>admin</strong></li>
        <li>Password: <strong><?= htmlspecialchars($newPassword) ?></strong></li>
    </ul>
    <p style="color: red; font-weight: bold;">⚠️ Now delete this file (reset_admin_password.php) from your project folder.</p>
<?php elseif ($ok && $affected === 0): ?>
    <h2 style="color: orange;">⚠️ No rows updated</h2>
    <p>The query ran but no admin row with username 'admin' was found. Check your <code>admin</code> table:</p>
    <p><a href="http://localhost/phpmyadmin/" target="_blank">Open phpMyAdmin</a> and run <code>SELECT * FROM admin;</code> to check.</p>
<?php else: ?>
    <h2 style="color: red;">❌ Update failed</h2>
    <p>Error: <?= htmlspecialchars(mysqli_error($conn)) ?></p>
<?php endif; ?>
</body>
</html>
